# Generated by Django 4.1.5 on 2023-02-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptids', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sightings',
            new_name='Sighting',
        ),
    ]
